# Generated by Django 3.2.7 on 2021-10-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_professor', models.CharField(max_length=30)),
                ('last_name_professor', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('date_of_employment', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
    ]
